### ISSUE TITLE
Failed to setup react-ui locally

### ISSUE THREAD

**Issue by anirudh-modi** [siddharthkp/react-ui#106]
Not sure if this should be here or somewhere else, but I was trying to setup the repo locally and while doing `yarn dev` in `packages/react-ui` I was getting the error

```
rollup v1.32.0
bundles index.js → dist/index.js...
[!] (plugin babel) Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/preset-env/lib/index.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/core/lib/config/files/index.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/core/lib/index.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /Users/anirudhmodi/Documents/oss/react-ui/packages/react-ui/rollup.config.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/rollup/dist/bin/rollup
index.js
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/preset-env/lib/index.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/core/lib/config/files/index.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/core/lib/index.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js
- /Users/anirudhmodi/Documents/oss/react-ui/packages/react-ui/rollup.config.js
- /Users/anirudhmodi/Documents/oss/react-ui/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/anirudhmodi/Documents/oss/react-ui/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```

**Comment by anirudh-modi** [comment]
@siddharthkp I have created a PR for the same, if you could review the same.
